CFLAGS=-Wall -g

all:
	make ex1
	make ex3
	make ex6
	make ex7
	make ex8
	make ex9
	make ex10
	make ex11
	make ex12
	make ex13
	make ex14
	make ex15
	make ex16

clean:
	rm -rf ex1
	rm -rf ex1.exe
	rm -rf ex1.dSYM
	rm -rf ex3
	rm -rf ex3.exe
	rm -rf ex3.dSYM
	rm -rf ex6
	rm -rf ex6.exe
	rm -rf ex6.dSYM
	rm -rf ex7
	rm -rf ex7.exe
	rm -rf ex7.dSYM
	rm -rf ex8
	rm -rf ex8.exe
	rm -rf ex8.dSYM
	rm -rf ex9
	rm -rf ex9.exe
	rm -rf ex9.dSYM
	rm -rf ex10
	rm -rf ex10.exe
	rm -rf ex10.dSYM
	rm -rf ex11
	rm -rf ex11.exe
	rm -rf ex11.dSYM
	rm -rf ex12
	rm -rf ex12.exe
	rm -rf ex12.dSYM
	rm -rf ex13
	rm -rf ex13.exe
	rm -rf ex13.dSYM
	rm -rf ex14
	rm -rf ex14.exe
	rm -rf ex14.dSYM
	rm -rf ex15
	rm -rf ex15.exe
	rm -rf ex15.dSYM
	rm -rf ex16
	rm -rf ex16.exe
	rm -rf ex16.dSYM
